apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-boot-knative-deployment
  labels:
    app: sample-boot-knative-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-boot-knative-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-boot-knative-app
        version: v1
    spec:
      containers:
      - name: sample-boot-knative-app
        image: bijukunjummen/sample-boot-knative-app:0.0.1-SNAPSHOT
        env:
        - name: VERSION
          value: "1.0"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - name: http
          containerPort: 8080
