apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: jib-gradle-build
spec:
  source:
    git:
      url: https://github.com/bijukunjummen/sample-boot-knative
      revision: master
  template:
    name: jib-gradle